### ISSUE TITLE
Link in new Tab

### ISSUE THREAD

**Issue by D3rJust1n** [st1020/kita#22]
I want to use kita for my blog, but I want links in a blog post to open in a new tab, just like the links for the social media platforms on the homepage. I have already tried to find the right file, but to no avail. 

I hope someone here can help me with this

**Comment by salif** [comment]
Hi, according to the Zola documentation you need to put this in your `config.toml`:
```toml
[markdown]
external_links_target_blank = true
```
